### ISSUE TITLE
Question about final_atten and fianl_polar

### ISSUE THREAD

**Issue by yxhhxy7** [XiaofeiWang2018/DeepGF#2]
Hi,

I'm trying to run your code and found that 'data/final_atten/' and 'data/final_polar/' are not provided.
How can I get these data?

Thanks.

**Comment by XiaofeiWang2018** [comment]
Hi,
Thanks for your attention. You can just generate the attention maps and the polar maps as described in the paper. Thenyou can put the generated results in the corresponding folds. If you still have any question, please contact me at xfwang@buaa.edu.cn
